Part 1:  Add fetching data about doctors from JSON Server and displaying them.
edyta555/patient-planner pull request #1
Opened 2022-08-05 08:29 UTC by edyta555

To connect to the JSON server you have to paste this command into the other terminal window:
npx json-server --watch data/db.json --port 8000

2022-08-05 15:14 UTC, bmichalowski-codilime requested changes

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/App.tsx
> +    (() => fetchItems())();
this is equal to `fetchItems()`

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/App.tsx
> +        const response = await fetch("http://localhost:8000/doctors");
It's good to build url which we import from one location. For example `backend_url + endpoint_url`, then it's easy to change the BE adress without messing around with the files.

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/App.tsx
> +        if (!response.ok) throw Error("Did not receive expected data");
This is not user frendly. Message will be displayed in the console, but nothing will happen in the app.

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/App.tsx
> +        <p>{fetchError}</p>
BE communication is not in our current scope, jYou can just cut it out.
In general, it is worth giving the user the option to go further - start next data request or provide mechanism for renewing the request after some time.

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/doctor-list/DoctorLIst.tsx
> +  console.log("doctorsData", doctorsData);
please remove console.log before pushing

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/doctor-list/DoctorLIst.tsx
> +      {doctorsData.map((doctorData) => (
As part of the handling of an empty list, we can display sth like "There are no doctors who meet your criteria. Please change your search criteria"

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/doctor-list/doctor-list.module.scss
> +  gap: 15px;
`gap` is related to `flex`. You can keep things grouped because it makes it easier to understand styles and maintain the code.

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/doctor-list/doctor-tile/DoctorTile.tsx
> +export const DoctorTile = ({ doctorData }: { doctorData: doctorDataType }) => {
I remembered another way:

type DoctorTileProps = {
 doctorData: doctorDataType;
};
export const DoctorTile = ({ doctorData }: doctorDataType) => {

2022-08-05 15:14 UTC, bmichalowski-codilime commented on src/doctor-list/doctor-tile/DoctorTile.tsx
> +    <div className={styles.tile} key={id}>
`first-column`, `second-column` - It is not a scalable solution. We can handle differences in the styles of the first / last list item in css.

2022-08-12 06:43 UTC, bmichalowski-fluxninja approved these changes

2022-08-12 06:49 UTC, merged